--------------------------------------------------------
--  PADRÃO PARA FLYWAY
--------------------------------------------------------
INSERT INTO TIMES (NOME) VALUES ('America');
INSERT INTO TIMES (NOME) VALUES ('Barueri');
INSERT INTO TIMES (NOME) VALUES ('Coritiba');
INSERT INTO TIMES (NOME) VALUES ('Brasil');

INSERT INTO CAMPANHAS (NOME,DATA_INICIAL,DATA_FINAL,TIME_ID) VALUES ('Campanha de lançamento.','2020-10-01','2020-10-03',1);
INSERT INTO CAMPANHAS (NOME,DATA_INICIAL,DATA_FINAL,TIME_ID) VALUES ('Campanha de começo de ano.','2020-10-01','2020-10-02',2);
INSERT INTO CAMPANHAS (NOME,DATA_INICIAL,DATA_FINAL,TIME_ID) VALUES ('Campanha de carnaval.','2020-02-21','2021-08-26',3);
INSERT INTO CAMPANHAS (NOME,DATA_INICIAL,DATA_FINAL,TIME_ID) VALUES ('Campanha de férias.','2021-07-01','2021-08-31',1);
INSERT INTO CAMPANHAS (NOME,DATA_INICIAL,DATA_FINAL,TIME_ID) VALUES ('Campanha do descobrimento.','1500-04-22','1500-04-22',4);